### ISSUE TITLE
Fedora Linux Error: SIGSEGV segmentation violation

### ISSUE THREAD

**Issue by flolu** [g45t345rt/g45w#7]
Thanks @g45t345rt for your efforts!

I was trying to build and run the wallet on Fedora Linux 38. So I followed these steps:

```bash
git clone https://github.com/g45t345rt/g45w
cd g45w
sudo dnf install -y gcc pkg-config wayland-devel libX11-devel libxkbcommon-x11-devel mesa-libGLES-devel mesa-libEGL-devel libXcursor-devel vulkan-headers
chmod +x build_go.sh
./build_go.sh linux amd64
./build/g45w_linux_amd64
```

But unfortunately, I get the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf156e3]

goroutine 101 [running]:
main.runApp()
        /home/username/Documents/g45w/main.go:164 +0x5a3
main.main.func1()
        /home/username/Documents/g45w/main.go:181 +0x19
created by main.main
        /home/username/Documents/g45w/main.go:180 +0x25
```

I'm using g45w v0.5.0 (33dfefaf7c34c2d72fea3edbb548663e749c58f1)

**Comment by g45t345rt** [comment]
It should be fixed. Can you `pull` and retry?

**Comment by flolu** [comment]
Thanks @g45t345rt! It's working now.
